kubernetesClusterDomain: cluster.local
myapp:
  hello:
    image:
      repository: quay.io/juouyang/golang-hello
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      requests:
        cpu: 5m
        memory: 16Mi
      limits:
        cpu: 50m
        memory: 64Mi
  nodeSelector:
    kubernetes.io/arch: arm64
  replicas: 1
service:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
