kubernetesClusterDomain: cluster.local
myapp:
  hello:
    image:
      repository: quay.io/juouyang/golang-hello
      tag: latest
    imagePullPolicy: IfNotPresent
    resources:
      limits:
        cpu: 100m
        memory: 32Mi
  nodeSelector:
    kubernetes.io/arch: amd64
    kubernetes.io/hostname: gcp-free-tier
  replicas: 1
service:
  ports:
  - port: 8080
    targetPort: 8080
  type: ClusterIP
