apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "golang-hello.fullname" . }}-demo
  labels:
  {{- include "golang-hello.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: argocd-demo.apps.k8s.juouyang.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "golang-hello.fullname" . }}-demo'
            port:
              number: 8080
        path: /
        pathType: Exact
  tls:
  - hosts:
    - argocd-demo.apps.k8s.juouyang.com
