apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ include "helm.fullname" . }}-ingress
  labels:
  {{- include "helm.labels" . | nindent 4 }}
spec:
  ingressClassName: nginx
  rules:
  - host: hello.apps.k8s.juouyang.com
    http:
      paths:
      - backend:
          service:
            name: '{{ include "helm.fullname" . }}-service'
            port:
              number: 8080
        path: /
        pathType: Exact
  tls:
  - hosts:
    - hello.apps.k8s.juouyang.com