demo:
  k8Scicd:
    image:
      repository: juouyang/k8scicd
      tag: latest
    imagePullPolicy: IfNotPresent
  nodeSelector:
    kubernetes.io/arch: arm64
  ports:
  - port: 8080
    targetPort: 8080
  replicas: 1
  type: ClusterIP
kubernetesClusterDomain: cluster.local
